@baseUrl = http://localhost:3333

@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "nicolas",
  "email": "nico",
  "password": "123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "nicolas1@teste.com",
  "password": "12345"
}

###

# @name create_question
POST {{baseUrl}}/question
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Qual a cor do cavalo branco de Napoleão?",
  "content": "A pergunta é autoexplicativa"
}